var traduction = {
  0: {
    LANG: "Français",
    LANGCODE: "FR",
    QUICK: "JOUER",
    DAiLYCHALLENGE: "Défi du jour",
    CUSTOM: "Partie personnalisée",
    ABOUT: "En savoir plus sur le jeu",
    LOAD: "CHARGER",
    ERROR_UNABLE: "IMPOSSIBLE DE CHARGER UNE PARTIE",
    COMPETITIVE: "Compétitif",
    SOLO: "SOLO / COOP",
    CLASSIC: "Classique",
    EXTREME: "Extrême",
    NIGHTMARE: "Cauchemar",
    CLASSICSUB: "",
    EXTREMESUB: "(Voir la règle)",
    NIGHTMARESUB: "(Voir la règle)",
    EASY: "Facile",
    MEDIUM: "Moyen",
    HARD: "Difficile",
    V4: "4",
    V5: "5",
    V6: "6",
    PLAYAGAME: "Jouer une partie",
    PLAY: "Générer une partie",
    LOADING: "CHARGEMENT...",
    CHECKCODE: "Tester un code",
    INPUTCODE: "Saisir votre code",
    TESTCODE: "Vérification",
    FALSECODE: "Ce n'est pas le bon code!",
    GOODCODE: "Félicitations! Vous avez réussi!",
    BEATTHEMACHINE: "Avez-vous battu la machine?",
    INPUTSOLOA: "Maintenant, pour savoir si vous avez battu la machine,",
    INPUTSOLOB: "Saisissez vos questions posées :",
    CLICBOXES: "Cliquez sur les cases pour les saisir",
    MAX3: "3 questions maximum par round !",
    ADDROUND: "Ajouter un round",
    DELROUND: "Supprimer",
    SUBMITSOLOQUESTIONS: "SOUMETTRE",
    SOCIALWIN: "Félicitation! <br/>Vous avez battu la machine!",
    SOCIALTIE: "Match nul contre la machine !",
    SOCIALLOSE: "La machine m'a battu !",
    YOUWIN: "VICTOIRE !!!",
    CANCEL: "RETOUR",
    SOLUTION: "Solution",
    BACK: "RETOUR",
    BACKHOME: "Retour à l'accueil",
    BACKTOGAME: "Retour à la partie",
    SHOW_SOLUTION: "Etes-vous sûr de voulir voir la solution ?",
    YES: "OUI",
    NO: "NON",
    CODE: "CODE",
    SHEET: "Télécharger des feuilles de notes",
    SEARCH: "Chercher une partie",
    STEP1: "Mode",
    STEP2: "Difficulté",
    STEP3: "Nombre de vérificateurs",
    CRITERIA: "Cartes Critères",
    CRITERIADOUBLE: "Cartes Critères (2 par vérificateur)",
    CRITERIAMIXED: "Cartes Critères (mélangées)",
    VERIFIER: "Cartes Vérification",
    SOLOMODE: "Mode solo",
    CHECKCODESOLO: "MACHINE",
    INPUTROUND: "NOMBRE DE ROUNDS",
    INPUTQUESTION: "NOMBRE DE QUESTIONS",
    WINSOLO0: "Oh! <br/> La machine vous a battu!",
    WINSOLO1: "Félicitation ! <br/> Même score que la machine!",
    WINSOLO2: "Félicitation ! <br/> Vous avez battu la machine!",
    ABOUTLINK: "http://www.scorpionmasque.com/fr/turingmachine",
    DATEFORMAT: "DD/MM/YYYY",
    DOWNLOADRULES: "Télécharger les règles du jeu",
    GAMEHISTORY: "Historique des parties",
    GAMETYPE: "Type de jeu",
    TEXT1: "Récupérer les cartes <span class='green'>critères</span> et les cartes vérifications dans la boite",
    INPUTGAMECODE: "Saisir le hash de la partie",
    CHOOSETYPE: "Choix du type de jeu",
    TRYAGAIN: "Recommencer",
    COMPARETOMACHINE: "Comparez-vous à la machine",
    VSMACHINETEXT1: "Vous avez trouvé le code <span class='success'>{$c}</span> en <span class='bolder'>{$r}</span> manches et <span class='bolder'>{$q}</span> questions",
    VSMACHINETEXT2: "La machine a réussi en <span class='bolder'>{$r}</span> manches et <span class='bolder'>{$q}</span> questions",
    INVITEFRIENDS: "Invitez vos amis à réaiser ce problème",
    COPY: "Copier",
    COPIED: "Copié!",
    EXTREMEMODE: "Mode Extrême: voir règles page 3",
    NIGHTMAREMODE: "Mode Cauchemard: voir règles page 3",
    SHARERESULTS: "Partagez votre résultat"
  },
  1: {
    LANG: "English",
    LANGCODE: "EN",
    QUICK: "PLAY",
    DAY: "Daily Challenge",
    DAiLYCHALLENGE: "Daily Challenge",
    CUSTOM: "Custm game",
    ABOUT: "About the game",
    LOAD: "LOAD",
    ERROR_UNABLE: "UNABLE TO LOAD GAME",
    COMPETITIVE: "Competitive",
    SOLO: "SOLO / COOP",
    CLASSIC: "Classic",
    EXTREME: "Extreme",
    NIGHTMARE: "Nightmare",
    CLASSICSUB: "",
    EXTREMESUB: "(See rulebook)",
    NIGHTMARESUB: "(See rulebook)",
    EASY: "Easy",
    MEDIUM: "Standard ",
    HARD: "Hard",
    V4: "4",
    V5: "5",
    V6: "6",
    PLAY: "GENERATE",
    PLAYAGAME: "Play a game",
    LOADING: "LOADING...",
    CHECKCODE: "Test a code",
    INPUTCODE: "Input your code",
    TESTCODE: "VERIFY",
    FALSECODE: "This code is not correct",
    GOODCODE: "Felicitation! This is the correct code!",
    BEATTHEMACHINE: "Did you beat the machine?",
    INPUTSOLOA: "Now, to know if you beat the machine,",
    INPUTSOLOB: "Input your question marks:",
    CLICBOXES: "Click on the boxes to fill them",
    MAX3: "3 questions maximum per round!",
    ADDROUND: "Add a round",
    DELROUND: "Remove last round",
    SUBMITSOLOQUESTIONS: "SUBMIT",
    SOCIALWIN: "I BEAT THE MACHINE!",
    SOCIALTIE: "I TIED THE MACHINE!",
    SOCIALLOSE: "THE MACHINE BEATS ME!",
    YOUWIN: "VICTORY!!!",
    CANCEL: "BACK",
    SOLUTION: "Solution",
    BACK: "BACK",
    BACKHOME: "Back to homepage",
    BACKTOGAME: "Back to game",
    SHOW_SOLUTION: "Are you sure that you want to see the solution?",
    YES: "YES",
    NO: "NO",
    CODE: "CODE",
    SHEET: "Download notes sheets",
    SEARCH: "Search a problem",
    STEP1: "Mode",
    STEP2: "Difficulty",
    STEP3: "Verificators",
    CRITERIA: "Criteria Cards",
    CRITERIADOUBLE: "Criteria Cards (2 on each verifier)",
    CRITERIAMIXED: "Criteria Cards (mixed)",
    VERIFIER: "Verification Cards",
    SOLOMODE: "Solo mode",
    CHECKCODESOLO: "MACHINE",
    INPUTROUND: "TOTAL ROUNDS PLAYED",
    INPUTQUESTION: "TOTAL QUESTIONS ASKED",
    WINSOLO0: "OH! <br/> You did not beat the machine.",
    WINSOLO1: "Congratulations!<br/> You tied the machine!",
    WINSOLO2: "Congratulations!<br/> You beat the machine!",
    ABOUTLINK: "http://www.scorpionmasque.com/en/turingmachine",
    DATEFORMAT: "MM/DD/YYYY",
    DOWNLOADRULES: "Download rules",
    GAMEHISTORY: "Game history",
    GAMETYPE: "Game type",
    TEXT1: "Retrieve <span class='green'>criteria</span> cards and verificators in the box",
    INPUTGAMECODE: "Input game hash",
    CHOOSETYPE: "Choose game type",
    TRYAGAIN: "Try again",
    COMPARETOMACHINE: "Compare with the machine",
    VSMACHINETEXT1: "You found the code <span class='success'>{$c}</span> <br/>in <span class='bolder'>{$r}</span> rounds and <span class='bolder'>{$q}</span> questions",
    VSMACHINETEXT2: "The machine found it in <span class='bolder'>{$r}</span> rounds and <span class='bolder'>{$q}</span> questions",
    INVITEFRIENDS: "Submit this problem to your friends",
    COPY: "Copy",
    COPIED: "Copied!",
    EXTREMEMODE: "Mode Extreme: see rulebook page 3",
    NIGHTMAREMODE: "Mode Nightmare: see rulebook page 3",
    SHARERESULTS: "Share your result with the hashtag #turingmachinegame"

  }
};

export default traduction;
